#!/bin/sh

#SBATCH --time=2:0:0 #2 hours
#SBTACH --ntasks=8
#SBATCH --nodes=8
#SBATCH --mem-per-cpu=1024

#SBATCH --output=./all.out

for test in $(ls tests)
do
    echo "===================="
    echo "${test##*/}"    
    echo "===================="

    echo 
    time ./base < tests/$test
    echo

    for n in 1 2 4 8
    do
        echo
        echo "o_parr $n"
        time  srun ./parr -N $n -n $n < tests/$test
        echo
    done
done
