#!/bin/bash

#SBATCH --time=01:00:00 # 1 hour

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32

#SBATCH --output=./output/final_32.out

CODE=diameter

for FILE in ./tests/*; do
    echo ${FILE##*/}
    time ./$CODE < $FILE
    echo
done
