#!/bin/bash

#SBATCH --time=01:00:00 # 1 hour

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8

#SBATCH --output=./output/f_symm.out

bash ../test.sh ../final_w_symm ../final_w_symm ../input
