#!/bin/sh

#SBATCH --time=00:30:00 # 30 mins
#SBATCH --nodes=8
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=4

#SBATCH --output=./final/final.out

    for nodes in 1 2 4 8
    do
        echo
        echo "========================================"
        echo "${arg##*\ }: $nodes     $arg"
        echo "========================================"
        time mpirun -np $nodes ./execs/final -2.0 1.0 -1.0 1.0 1000 10000 -1 1.0 0.0 1.0 1000 10000 -2.0 -1.0 -0.5 1.0 20000 10000 -1 1.0 0.0 2.0 1000 30000 -2.0 1.0 -2.0 1.0 10000 5000 -1 1.0 0.5 1.0 20000 3000 -2.0 -0.5 0.5 1.0 1000 1000000        
echo
    done

